apiVersion: apps/v1
kind: Deployment
metadata:
  name: kws-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kws-app
  template:
    metadata:
      labels:
        app: kws-app
    spec:
      containers:
      - name: kws-cluster
        image: gcr.io/end-to-end-keyword-spotting/kws:v0