# Name of the workflow to run automated tests
name: Tests

# Run workflow on every push to main branch
on:
  push:
    branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
        
        - name: Set up Python
          uses: actions/setup-python@v2
        
          with: 
            python-version: 3.10.4  # Specify the version you need
        
        - name: Install Dependencies
          run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
        
        - name: Run Unit Tests
          run: |
              pytest tests/pytest.py --junitxml=pytest-report.xml
          continue-on-error: false

        - name: Upload test results
          if: always()
          uses: actions/upload-artifact@v2
          with:
            name: test-results
            path: pytest-report.xml
    
        - name: Notify on success
          if: success()
          run: echo "Tests passed successfully"
    
        - name: Notify on failure
          if: failure()
          run: echo "Tests failed"
        
